[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dd-license-attribution"
version = "0.5.0"
description = "A tool that collects license and copyright information for third party dependencies of a project."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Damian Vicino", email = "damian.vicino@datadoghq.com" },
    { name = "Ara Pulido", email = "ara.pulido@datadoghq.com" }
]
urls = { "Homepage" = "https://github.com/DataDog/dd-license-attribution" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "agithub",
    "scancode-toolkit",
    "typer",
    "pytz",
    "giturlparse",
    "requests",
    "spdx-tools==0.7", # pinned to 0.7 to avoid breaking changes
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "mypy",
    "black",
    "isort",
    "mutmut",
    "types-pytz",
    "types-requests"
]

[project.scripts]
dd-license-attribution = "dd_license_attribution.cli.main_cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--cov=src/dd_license_attribution"
xfail_strict = "True"
filterwarnings = [
    "ignore::UserWarning:typecode.magic2:"
]

[tool.mutmut]
paths_to_mutate = ["src/"]
runner = "python -m pytest"

[tool.mypy]
strict = "True"
disallow_untyped_calls = "True"
disallow_untyped_defs = "True"
disallow_incomplete_defs = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
warn_redundant_casts = "True"

[[tool.mypy.overrides]]
module = "scancode.api"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "scancode"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "scancode.api"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "agithub.GitHub"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "giturlparse"
ignore_missing_imports = true

[tool.isort]
profile = "black"
