name: Run Contract Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TERM: dumb

    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: "pip" # caching pip dependencies

      - name: Install Rust tooling
        run: |
          curl --proto '=https' --tlsv1.2 --silent --show-error --fail https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
          "${HOME}/.cargo/bin/cargo" install dd-rust-license-tool

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run contract tests
        run: pytest tests/contract
